/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  Hello as AeHello
} from './components/hello/hello';

declare global {
  interface HTMLAeHelloElement extends AeHello, HTMLStencilElement {
  }
  var HTMLAeHelloElement: {
    prototype: HTMLAeHelloElement;
    new (): HTMLAeHelloElement;
  };
  interface HTMLElementTagNameMap {
    "ae-hello": HTMLAeHelloElement;
  }
  interface ElementTagNameMap {
    "ae-hello": HTMLAeHelloElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ae-hello": JSXElements.AeHelloAttributes;
    }
  }
  namespace JSXElements {
    export interface AeHelloAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
